version: '2'
services:
  webapp:
    image: amsdard.io/{name}/webapp:1.0
    stdin_open: true
    tty: true
    links:
    - mysql:mysql
    volumes:
      - {name}-webapp-config:/opt/app/config
      - {name}-webapp-cache:/opt/app/cache
      - {name}-webapp-files:/opt/public/files
      - {name}-webapp-thumbs:/opt/public/thumbs
    labels:
      traefik.enable: 'true'
      traefik.domain: app.amsdard.io
      io.rancher.container.pull_image: always
      traefik.alias: {name}
  mysql:
    image: mariadb:10
    stdin_open: true
    volumes:
    - {name}-mysql-var-lib-mysql:/var/lib/mysql
    tty: true
